config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :events
  

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :month
end

app/models/event.rb
class Event < ApplicationRecord
  # has_many :occurrence

  def create

  end

  # def update
  # end

  def delete
  end

  def findStartMonth
    # @month = month
    @numMonth
    case self.startMonth
    when "January"
      @numMonth = 1
    when "February"
      @numMonth = 2
    when "March"
      @numMonth = 3
    when "April"
      @numMonth = 4
    when "May"
      @numMonth = 5
    when "June"
      @numMonth = 6
    when "July"
      @numMonth = 7
    when "August"
      @numMonth = 8
    when "September"
      @numMonth = 9
    when "October"
      @numMonth = 10
    when "November"
      @numMonth = 11
    when "December"
      @numMonth = 12

    end
    @numMonth
  end

  def findEndMonth
    # @month = month
    @numMonthEnd
    case self.endMonth
    when "January"
      @numMonthEnd = 1
    when "February"
      @numMonthEnd = 2
    when "March"
      @numMonthEnd = 3
    when "April"
      @numMonthEnd = 4
    when "May"
      @numMonthEnd = 5
    when "June"
      @numMonthEnd = 6
    when "July"
      @numMonthEnd = 7
    when "August"
      @numMonthEnd = 8
    when "September"
      @numMonthEnd = 9
    when "October"
      @numMonthEnd = 10
    when "November"
      @numMonthEnd = 11
    when "December"
      @numMonthEnd = 12

    end
    @numMonthEnd
  end

  def occurrenceLogic
    @newStartMonth = self.findStartMonth
    @newEndMonth = self.findEndMonth
    @newStartDate = self.startDate
    @newEndDate = self.endDate
    @evenOrOdd = self.findStartMonth + 2


    while @newStartMonth <= @newEndMonth
      self.occurrenceCreator

      case self.reoccurType
      when "Daily"
        @newStartDate += 1
        if @evenOrOdd % 2 == 0
          if @newStartDate > 30
            @newStartDate = (@newStartDate - 30)
            @newStartMonth += 1
          end

        else
            if @newStartDate > 31
              @newStartDate = (@newStartDate - 31)
              @newStartMonth += 1
              @evenOrOdd += 1
            end

        end

      when "Weekly"
        @newStartDate += 7
        if @evenOrOdd % 2 == 0

          if @newStartDate > 30
            @newStartDate = (@newStartDate - 30)
            @newStartMonth += 1
          end
        else
            if @newStartDate > 31
              @newStartDate = (@newStartDate - 31)
              @newStartMonth += 1
              @evenOrOdd += 1
            end

        end
      when "Monthly"
        @newStartMonth += 1
      when "Quarterly"
        @newStartMonth += 3
      end

    end
  end

  def occurrenceCreator
    @newId = self.id.to_i
    @x = Occurrence.new(eventID: self.id, startMonthO: @newStartMonth, startdateO: @newStartDate, endDateO: @newEndDate, endMonthO: @newEndMonth, nameO: self.name, descriptionO: self.description)
    @x.save
    @x
  end

  def destroyOccurrence
    @occur = Occurrence.all

    @occur.each do |t|
      # case t.eventID
      # when self.id.to_i
      #   t.destroy
      # end
      @oldId = self.id.to_i
      if t.eventID == @oldId
        t.destroy
      end
    end
  end

end

app/models/month.rb
class Month < ApplicationRecord
  has_many :days
end

app/models/occurrence.rb
class Occurrence < ApplicationRecord
  # belongs_to :event, required: false

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params.require(:event).permit(:name, :description, :reoccur, :reoccurType, :startMonth, :startDate, :endMonth, :endDate))

    @event.save

      @event.occurrenceLogic


 redirect_to @event
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(params.require(:event).permit(:name, :description, :reoccur, :reoccurType, :startMonth, :startDate, :endMonth, :endDate))
      # @event.update(:name => name)
      @event.destroyOccurrence
      @event.occurrenceLogic
      redirect_to @event
    else
      render 'edit'
    end
  end

  def show
    @event = Event.find(params[:id])
    @occur = Occurrence.all
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroyOccurrence
    @event.destroy

    redirect_to events_path
  end

private
  def event_params
    params.require(:event).permit(:name, :description, :reoccur, :reoccurType, :startMonth, :startDate, :endMonth, :endDate)
  end

end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @event = Event.all
    # @occur = Occurrence.all
    @occur = Occurrence.all 

  end

  def create
    # @event = Event.new(event_params)
    # @event.save
    #
    # @occur = Occurrence.new(:eventID = @event.id, :month, :date)

  end

  def show

  end

  # private
  # def event_params
  #   params.require(:event).permit(:name, :description, :reoccur, :reoccurType, :startTime, :endTime)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>


<%= form_with model: @event, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :reoccur %><br>
    <%=form.select :reoccur, options_for_select(["Yes", "No"])%><br>
    <!-- <%= form.text_field :reoccur %> -->
  </p>

  <p>
    <%= form.label :reoccurType %><br>
    <%=form.select :reoccurType, options_for_select(["Daily", "Weekly", "Monthly", "Quarterly"])%><br>
    <!-- <%= form.text_field :reoccurType %> -->
  </p>
  <p>
    <%= form.label :startMonth %><br>
    <%=form.select :startMonth, options_for_select(["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])%><br>
    <!-- <%= form.text_field :startTime %> -->
  </p>
  <p>
    <%= form.label :startDate %><br>
    <%=form.select :startDate, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])%><br>
    <!-- <%= form.text_field :startTime %> -->
  </p>
  <p>
    <%= form.label :endMonth %><br>
    <%=form.select :endMonth, options_for_select(["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])%><br>
    <!-- <%= form.text_field :startTime %> -->
  </p>
  <p>
    <%= form.label :endDate %><br>
    <%=form.select :endDate, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])%><br>
    <!-- <%= form.text_field :startTime %> -->
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/events/index.html.erb
<h1>List of Events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.description %></td>
      <td><%= link_to 'Show', event_path(event) %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>To make a new event</h1>


<%= form_with scope: :event, url: events_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :reoccur %><br>
    <%=form.select :reoccur, options_for_select(["Yes", "No"])%><br>
    <!-- <%= form.text_field :reoccur %> -->
  </p>

  <p>
    <%= form.label :reoccurType %><br>
    <%=form.select :reoccurType, options_for_select(["Daily", "Weekly", "Monthly", "Quarterly"])%><br>
    <!-- <%= form.text_field :reoccurType %> -->
  </p>
  <p>
    <%= form.label :startMonth %><br>
    <%=form.select :startMonth, options_for_select(["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])%><br>
    <!-- <%= form.text_field :startTime %> -->
  </p>
  <p>
    <%= form.label :startDate %><br>
    <%=form.select :startDate, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])%><br>
    <!-- <%= form.text_field :startTime %> -->
  </p>
  <p>
    <%= form.label :endMonth %><br>
    <%=form.select :endMonth, options_for_select(["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])%><br>
    <!-- <%= form.text_field :startTime %> -->
  </p>
  <p>
    <%= form.label :endDate %><br>
    <%=form.select :endDate, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])%><br>
    <!-- <%= form.text_field :startTime %> -->
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/events/show.html.erb
<%= link_to 'Edit', edit_event_path(@event) %>
<%= link_to 'Back', events_path %>
<h1>Event</h1>
<p>
  <strong>Event Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Event Description:</strong>
  <%= @event.description %>
</p>
<p>
  <strong>Event Start Month:</strong>
  <%= @event.startMonth %>
</p>

<p>
  <strong>Event End Month:</strong>
  <%= @event.endMonth %>
</p>
<hr>
<h2>Occurrences of Event</h2>
<hr>

  <% @occur.each do |t| %>
    <% if t.eventID == @event.id %>
    <p>Event Name: <%=t.nameO%></p>
    <p>Event Description: <%=t.descriptionO%></p>
    <p>Event Date: <%= t.startMonthO%> / <%=t.startdateO%> / 2018</p>

    <hr>
    <% end %>


  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M76Calendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>